### ISSUE TITLE
Segfault if connection fails

### ISSUE THREAD

**Issue by MarcusZuber** [ufo-kit/uca-net#16]
If a net camera is started and no connection can be establishes, a segmentation fault is caused (which is quite ugly if this kills my concert session if I have a typo in the IP of the camera server).

To fix this, here https://github.com/ufo-kit/uca-net/blob/893456b0863d58e4c6b3ae12bfd1a74116266652/uca-net-camera.c#L618 an else, that handles the NULL case would be required.
I guess for someone with more glib experience than me this will be a single line to properly pass the error.

**Comment by tfarago** [comment]
I will do this.
