### ISSUE TITLE
reading properties while streaming fails

### ISSUE THREAD

**Issue by MarcusZuber** [ufo-kit/uca-net#3]
When the net-camera is streaming and at the client properties are read, the frame and the properties are mixed up resulting in broken frames and warnings "could not get property: Reply does not match request"

In concert:
```
camera = Camera('net', {'host': 'host:port'}
camera.stream(viewer())
camera
```

We have set everything up in the Lab, if you want to test this without compiling all on windows...

**Comment by ltjax** [comment]
Seems like the answers on the net camera are not correctly matched to the requests. Maybe create a new connection for each request and increase the incoming connection count in ucad?

**Comment by matze** [comment]
First of all: yes, the current protocol assumes strict adherence to a synchronous request-reply policy, interleaving requests is going to mess things up. Yes, one connection per request could fix this but I assume this is going to kill performance. Even the web folks are acknowledging this with HTTP/2.

I see two options to fix this:

1) We block/enqueue requests until all previous requests are handled. This is relatively simple to do and does not change the underlying message protocol. The downside is that requests are serialized causing large indeterministic jitters. For example, we could have a situation like above where all the properties have to be transmitted before we can get a new frame. One solution would be prioritizing requests but that could lead to priority inversion ... :unamused: 
2) We properly multiplex the requests which means buffering replies on the receiving ends which means more logic and also increasing latencies and jitter.

I don't know about your specific use case and the timing sensitivity of your application but I still would favor of fixing this with the first option. Opinions?

**Comment by ltjax** [comment]
Web folks are also thinking about orders of magnitude more requests, where the protocol overhead really does matter. I don't think it's a problem here, where there's really only one client.

Blocking won't work for things that require asynchronicity. For example using the software trigger source. The trigger will have to happen during a grab!

The way I see it, multiple connections do the multiplexing. To get rid of the additional overhead, you can pool the connections and essentially do the enqueuing when connections on the client are free. That way, it'll behave like now for the sequential case, and just generate new connections for parallel access.

**Comment by matze** [comment]
> To get rid of the additional overhead, you can pool the connections and essentially do the enqueuing when connections on the client are free.

This leads to the exact same problem you outline for my blocking proposal. If the pool is too small and the number of interdependent requests too large you also run into a deadlock.

**Comment by ltjax** [comment]
Only if the pool is fixed size!

**Comment by matze** [comment]
Okay, I will come up with a PR. If performance sucks it's on you to fix it :smile:
